apiVersion: v1
kind: service
metaData: 
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: netflix-app